import { connectDB } from '../Database/mongoose.js';
import OpticalFrame from '../Models/OpticalFrame.js';

export const DUMMY_PRODUCTS = [
  {
    name: 'RS Titanium Rimless UltraLite Air',
    brand: 'RS Signature Premium',
    category: 'FRAMES',
    lensType: 'Blue Cut Digital Anti-Glare Lens',
    frameShape: 'Rectangle / Sleek Rimless',
    material: 'Pure Japanese Titanium (Featherweight 8g)',
    priceRange: '₹1,499 - ₹3,499',
    description: 'Featherweight pure titanium rimless specs designed for all-day computer screen work and ear comfort.',
    imageUrl: '/images/optical_titanium_specs.jpg',
    isTrending: true,
  },
  {
    name: 'RS Flexi-Shield Acetate Prescription Frame',
    brand: 'RS Ergonomic Optical',
    category: 'FRAMES',
    lensType: 'Progressive HD Multi-Focal Compatible',
    frameShape: 'Classic Wayfarer / Oval',
    material: 'High-Grade Flexible Italian Acetate',
    priceRange: '₹999 - ₹2,499',
    description: 'Durable flex-hinge frame ideal for active daily use, reading, and multifocal prescriptions.',
    imageUrl: '/images/optical_acetate_frames.jpg',
    isTrending: true,
  },
  {
    name: 'RS BlueGuard Digital Anti-Glare Lenses',
    brand: 'RS Power Lens Series',
    category: 'POWER_LENSES',
    lensType: 'Blue Light Filtering + Anti-Reflective Coating',
    frameShape: 'Universal Fitting',
    material: 'High Index Polycarbonate 1.67',
    priceRange: '₹799 - ₹1,999',
    description: 'Blocks harmful blue light emitted from mobiles, laptops, and LED screens to reduce eye fatigue.',
    imageUrl: '/images/optical_titanium_specs.jpg',
    isTrending: true,
  },
  {
    name: 'RS AirFit Minimalist Half-Rim Glasses',
    brand: 'RS Signature Premium',
    category: 'FRAMES',
    lensType: 'Anti-Reflective Single Vision Lens',
    frameShape: 'Rectangle Half-Rim',
    material: 'Stainless Steel Alloy',
    priceRange: '₹1,299 - ₹2,799',
    description: 'Professional executive half-rim frame with spring hinges and adjustable nose pads.',
    imageUrl: '/images/optical_titanium_specs.jpg',
    isTrending: false,
  },
  {
    name: 'RS Progressive Max Clear Vision Lenses',
    brand: 'RS Power Lens Series',
    category: 'POWER_LENSES',
    lensType: 'No-Line Seamless Progressive Multi-Focal',
    frameShape: 'Universal Fitting',
    material: 'High Index Resin 1.60',
    priceRange: '₹1,899 - ₹4,499',
    description: 'Smooth transition between distance, intermediate, and near reading powers without line distraction.',
    imageUrl: '/images/optical_acetate_frames.jpg',
    isTrending: true,
  },
  {
    name: 'RS Polarized UV400 Prescription Sunglasses',
    brand: 'RS Urban Sunwear',
    category: 'SUNGLASSES',
    lensType: 'Category 3 Polarized UV400 Protection',
    frameShape: 'Aviator / Square',
    material: 'TR90 Matte Finish',
    priceRange: '₹1,199 - ₹2,899',
    description: 'Polarized glare reduction sunglasses compatible with custom prescription power lenses.',
    imageUrl: '/images/optical_sunglasses.jpg',
    isTrending: true,
  },
  {
    name: 'RS Junior Flex Unbreakable Kids Specs',
    brand: 'RS Kids Care',
    category: 'KIDS_GLASSES',
    lensType: 'Impact Resistant Polycarbonate Safety Lens',
    frameShape: 'Round Ergonomic',
    material: 'Non-Toxic Soft Silicone & TR90',
    priceRange: '₹699 - ₹1,599',
    description: 'Flexible, bendable, non-toxic frames designed for active children aged 3-12 years.',
    imageUrl: '/images/optical_acetate_frames.jpg',
    isTrending: false,
  },
  {
    name: 'RS Vintage Browline Acetate Frame',
    brand: 'RS Heritage Series',
    category: 'FRAMES',
    lensType: 'Photochromic Transition (Light to Dark)',
    frameShape: 'Clubmaster / Browline',
    material: 'Handcrafted Acetate & Metal Accent',
    priceRange: '₹1,599 - ₹3,299',
    description: 'Vintage retro browline frame suitable for transition lenses and formal wear.',
    imageUrl: '/images/optical_acetate_frames.jpg',
    isTrending: false,
  },
  {
    name: 'RS PhotoMax Day-Night Transition Lenses',
    brand: 'RS Power Lens Series',
    category: 'POWER_LENSES',
    lensType: 'Fast Reacting Photochromic UV Sensing',
    frameShape: 'Universal Fitting',
    material: 'Trivex High-Impact Resistance',
    priceRange: '₹1,399 - ₹3,199',
    description: 'Automatically darkens outdoors under sunlight and clears indoors instantly.',
    imageUrl: '/images/optical_titanium_specs.jpg',
    isTrending: true,
  },
  {
    name: 'RS SportFlex Wrap-Around Prescription Glasses',
    brand: 'RS Active Sports',
    category: 'SUNGLASSES',
    lensType: 'Anti-Fog Scratch-Resistant Hard Coat',
    frameShape: 'Curved Sport Wrap',
    material: 'TR90 Thermoplastic',
    priceRange: '₹1,499 - ₹2,999',
    description: 'Ergonomic wrap-around frame with sweat-resistant grip for sports and outdoor driving.',
    imageUrl: '/images/optical_sunglasses.jpg',
    isTrending: false,
  },
];

export class SeedService {
  static async seedInitialData() {
    await connectDB();
    await OpticalFrame.deleteMany({});
    await OpticalFrame.insertMany(DUMMY_PRODUCTS);
    return { success: true, message: '10 optical products seeded with realistic product photography.' };
  }
}
